services:
  # DEV SERVER
  - type: web
    name: demo-frontend2-dev
    env: node
    repo: https://github.com/BROKLab/brok-monorepo
    branch: robertosnap/sym-31-demo-side
    region: frankfurt
    buildCommand: 'pnpm unlink @brok/sdk2; pnpm i --no-frozen-lockfile; pnpm build'
    startCommand: 'pnpm start'
    plan: Starter
    rootDir: packages/demo-frontend2
    buildFilter:
      paths:
      # Changes to the `frontend` directory do not match this pattern.
      - packages/demo-frontend2/**
      - packages/sdk2/**
    envVars:
    - key: NEXT_PUBLIC_CERAMIC_URL
      sync: false
    - key: NEXT_PUBLIC_SECRET
      sync: false
    - key: NEXT_PUBLIC_ETHEREUM_RPC
      sync: false
    - key: NEXT_PUBLIC_THE_GRAPH_URL
      sync: false
    - key: NEXT_PUBLIC_BROK_ENVIRONMENT
      sync: false
