services:
  # DEV SERVER
  - type: web
    name: demo-site-dev
    env: node
    repo: https://github.com/BROKLab/brok-monorepo
    branch: robertosnap/sym-31-demo-side
    region: frankfurt
    buildCommand: 'pnpm i; pnpm unlink @brok/sdk; pnpm i --frozen-lockfile; pnpm build'
    startCommand: 'pnpm start'
    plan: Free
    rootDir: packages/demo-site
    envVars:
      - fromGroup: brokDev-next

  # - type: web
  #   name: demo-frontend-dev
  #   env: node
  #   repo: https://github.com/BROKLab/brok-monorepo
  #   branch: dev
  #   region: frankfurt
  #   buildCommand: 'pnpm i; pnpm unlink @brok/sdk; pnpm i --frozen-lockfile; pnpm build'
  #   startCommand: 'pnpm start'
  #   plan: Free
  #   rootDir: packages/demo-frontend
  #   # buildFilter:
  #   #   paths:
  #   #   # Changes to the `frontend` directory do not match this pattern.
  #   #   - packages/demo-frontend2/**
  #   #   - packages/sdk2/**
  #   envVars:
  #     - fromGroup: brokDev-next
    
