import { Button, Container, styled } from '@nextui-org/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const StyledApp = styled("div", {
  dflex: "center",
  flexDirection: "column",
  minHeight: "100vh"
});

const Home: NextPage = () => {
  return (
    <StyledApp >
      <Head>
        <title>BRØK aksjeeierbok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
        <Button>Click me</Button>
        </Container>
      </main>

      <footer >
        <Container fluid={true}><span>Del av Brønnøysundregistrene Sandkasse</span></Container>
      </footer>
    </StyledApp>
  )
}

export default Home
