import { Button, Container, styled } from '@nextui-org/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { SDK } from "@brok/sdk2"
import { useEffect } from 'react'


const StyledApp = styled("div", {
  dflex: "center",
  flexDirection: "column",
  minHeight: "100vh"
});

const Home: NextPage = () => {
  const createCapTable = async () => {
    const sdk = await SDK.init({ ceramicUrl: "https://ceramic-clay.3boxlabs.com", ethereumRpc: "http://127.0.0.1:8545/", secret: "kid letter bicycle motion maid token change couch useless seven boost strategy", theGraphUrl: "http://localhost:8000/subgraphs/name/brok/captable", env: "brokLocal" });
    const address = await sdk.createCapTable({
      name: "Test 535325",
      orgnr: "1241241234",
      shareholders: [
        {
          amount: "6664444",
          birthDate: "230188",
          countryCode: "NO",
          name: "TES PERSON",
          partition: "ordinære",
          postalcode: "50553"
        }
      ]
    })
    console.log("CapTableAddress", address)
    const capTable = await sdk.getCapTable(address)
    // const transferResult = await t.context.sdk.transfer(t.context.capTableAddress, [
    //   {
    //     amount: '100',
    //     from: capTable.shareholders[0].ethAddress,
    //     to: shareholderB.ethAddress,
    //     partition: 'ordinære',
    //   },
    // ]);
    console.log("CapTable", capTable)
  }

  return (
    <StyledApp >
      <Head>
        <title>BRØK aksjeeierbok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Button onClick={() => createCapTable()}>Create</Button>
          <Button onClick={() => createCapTable()}>Create</Button>
        </Container>
      </main>

      <footer >
        <Container fluid={true}><span>Del av Brønnøysundregistrene Sandkasse</span></Container>
      </footer>
    </StyledApp>
  )
}

export default Home
