import { Button, Container, styled } from '@nextui-org/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { SDK } from "@brok/sdk2"
import { useEffect } from 'react'


const StyledApp = styled("div", {
  dflex: "center",
  flexDirection: "column",
  minHeight: "100vh"
});

const Home: NextPage = () => {
  useEffect(() => {
    let subscribed = true
    const doAsync = async () => {
      const sdk = await SDK.init({ ceramicUrl: "http://localhost:7007/", ethereumRpc: "http://127.0.0.1:8545/", secret: "kid letter bicycle motion maid token change couch useless seven boost strategy", theGraphUrl: "http://localhost:8000/subgraphs/name/brok/captable", env: "brokLocal" });
      console.log(sdk)
      const address = await sdk.createCapTable({
        name: "Test 2413251351",
        orgnr: "412412451",
        shareholders: [
          {
            amount: "1322",
            birthDate: "230188",
            countryCode: "NO",
            name: "TES PERSON",
            partition: "ordinære",
            postalcode: "50553"
          }
        ]
      })
      console.log(address)
      if (subscribed) {
      }
    };
    doAsync();
    return () => { subscribed = false }
  }, [])
  return (
    <StyledApp >
      <Head>
        <title>BRØK aksjeeierbok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Button>{(2)}</Button>
        </Container>
      </main>

      <footer >
        <Container fluid={true}><span>Del av Brønnøysundregistrene Sandkasse</span></Container>
      </footer>
    </StyledApp>
  )
}

export default Home
